apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seqrepo-claim
  namespace: genetics
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: variant-decoder
  namespace: genetics
  labels:
    app: variant-decoder
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: variant-decoder
  template:
    metadata:
      labels:
        app: variant-decoder
        tier: backend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
        - image: kallepan/variant-decoder:v2
          imagePullPolicy: Always
          name: variant-decoder
          envFrom:
            - secretRef:
                name: variant-decoder
          ports:
            - containerPort: 9000
              name: gunicorn
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "1Gi"
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
          volumeMounts:
            - name: seqrepo
              mountPath: /data/seqrepo
          readinessProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 360 # 1 hour
            tcpSocket:
              port: 9000
      volumes:
        - name: seqrepo
          persistentVolumeClaim:
            claimName: seqrepo-claim      
---
apiVersion: v1
kind: Service
metadata:
  name: variant-decoder
  namespace: genetics
  labels:
    app: variant-decoder
    tier: backend
spec:
  ports:
    - port: 80
      name: gunicorn
      targetPort: 9000
      protocol: TCP
  selector:
    app: variant-decoder
    tier: backend
  type: ClusterIP